### ISSUE TITLE
using snippet - I'm trying to send an event and I get this error

### ISSUE THREAD

**Issue by evanjmg** [mixpanel/mixpanel-js#117]
failed to send event  -> TypeError: a.search is not a function
    at Object.rd (http://cdn.mxpnl.com/libs/mixpanel-2-latest.min.js:31:405)
    at Object.sd (http://cdn.mxpnl.com/libs/mixpanel-2-latest.min.js:32:132)
    at o.ec (http://cdn.mxpnl.com/libs/mixpanel-2-latest.min.js:57:305)
    at h.I (http://cdn.mxpnl.com/libs/mixpanel-2-latest.min.js:67:160)
    at Object.<anonymous> (http://localhost:8888/f8f7011c77d565f1f9b7.js:72928:17)
    at Object.<anonymous> (http://localhost:8888/f8f7011c77d565f1f9b7.js:70459:41)
    at Array.map (native)
    at Object.<anonymous> (http://localhost:8888/f8f7011c77d565f1f9b7.js:70450:48)
    at http://localhost:8888/f8f7011c77d565f1f9b7.js:9720:19
    at Object.invoke [as $inject] (http://localhost:8888/f8f7011c77d565f1f9b7.js:13223:20)
Errors in this function: 
    rd: function(a) {
                return 0 === a.search("https?://(.*)google.([^/?]*)") ? "google" : 0 === a.search("https?://(.*)bing.com") ? "bing" : 0 === a.search("https?://(.*)yahoo.com") ? "yahoo" : 0 === a.search("https?://(.*)duckduckgo.com") ? "duckduckgo" : n
            }, - what is this?

**Comment by tdumitrescu** [comment]
This comes from the lib's [search-engine referrer parsing](https://github.com/mixpanel/mixpanel-js/blob/b4cf2c5cb900fbb102370c01553e9a70f4c6e2d0/src/utils.js#L1340-L1352), which gets passed the [string in `document.referrer`](https://github.com/mixpanel/mixpanel-js/blob/b4cf2c5cb900fbb102370c01553e9a70f4c6e2d0/src/mixpanel-core.js#L1080).

Which browser/OS are you using? What is the type/value of `document.referrer` on your page?

**Comment by evanjmg** [comment]
Ah, thanks I found that I had a form with the name attribute referrer (for referrals etc) and than turned my document.referrer into a dom element. Definitely weird.
